packages:
  - apps/*
  - packages/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': 0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/lodash': ^4.17.20
  '@types/node': 25.0.1
  bun-types: ^1.3.2
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.3.5
  ky: ^1.14.1
  lodash: ^4.17.21
  server-only: ^0.0.1
  superjson: 2.2.6
  tsdown: ^0.16.1
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  auth:
    '@better-auth/expo': 1.4.6
    'better-auth': 1.4.6
  chiastack:
    '@chiastack/eslint': 2.0.4
    '@chiastack/tsconfig': 2.1.1
  eslint:
    '@eslint/js': 9.39.1
    eslint: 9.39.1
  heroui:
    '@heroui/react': beta
    '@heroui/styles': beta
  next:
    '@next/bundle-analyzer': 16.0.3
    '@next/eslint-plugin-next': 16.0.3
    '@next/third-parties': 16.0.3
    next: 16.0.3
  orpc:
    '@orpc/client': 1.12.2
    '@orpc/contract': 1.12.2
    '@orpc/server': 1.12.2
    '@orpc/tanstack-query': 1.12.2
  react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.2
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.3
    react-dom: ^19.2.3
  tailwindcss:
    '@tailwindcss/postcss': 4.1.17
    tailwindcss: 4.1.18
  tanstack:
    '@tanstack/react-query': 5.90.12

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@shopify/react-native-skia'

strictPeerDependencies: false
